In [1]:
import numpy as np
# --------------------------------------------
# 1. creating an array
# --------------------------------------------

# using a list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1:", arr1)

#using nested list(matrix)
arr2 = np.array([[1,2, 3], [4,5,6]])
print("Array 2(2D array):\n", arr2)

#using arange, linspace, zeros,ones, eye
arr_arange = np.arange(0, 10, 2)  # from 0 to 10 with step 2
print("Array 3 (arange):", arr_arange)

arr_linspace = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("Array 4 (linspace):", arr_linspace)

arr_ones = np.ones((3,2))  # 3x2 array of ones
print("Array 5 (ones):\n", arr_ones)   

arr_eye = np.eye(3)  # 3x3 identity matrix
print("Array 6 (identity matrix):\n", arr_eye) 


Array 1: [1 2 3 4 5]
Array 2(2D array):
 [[1 2 3]
 [4 5 6]]
Array 3 (arange): [0 2 4 6 8]
Array 4 (linspace): [0.   0.25 0.5  0.75 1.  ]
Array 5 (ones):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array 6 (identity matrix):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# --------------------------------------------
# 2. array attributes
# --------------------------------------------

print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Number of dimensions of arr2:", arr2.ndim)
print("Data type of arr2:", arr2.dtype)
print("Item size of arr2 (in bytes):", arr2.itemsize)

Shape of arr2: (2, 3)
Size of arr2: 6
Number of dimensions of arr2: 2
Data type of arr2: int64
Item size of arr2 (in bytes): 8


In [4]:
# --------------------------------------------
# 3. array indexing and slicing
# --------------------------------------------

# 1D array indexing and slicing
arr = np.array([10,20,30,40,50])
print("Original array:", arr)
print("Element at index 2:", arr[2])  # 30
print("Last element: ",  arr[-1])  # 50
print("Slice from index 1 to 4:", arr[1:4])  # [20 30 40]

# 2D array indexing and slicing
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Original 2D array:\n", arr_2d)
print("First row:", arr_2d[0])  # [1 2 3]
print("Second column:", arr_2d[:, 1])  # [2 5 8]
print("Submatrix:\n", arr_2d[0:2, 1:3])  # [[2 3] [5 6]]



Original array: [10 20 30 40 50]
Element at index 2: 30
Last element:  50
Slice from index 1 to 4: [20 30 40]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Submatrix:
 [[2 3]
 [5 6]]


In [5]:
# --------------------------------------------
# 4. Basic Operations
# --------------------------------------------  

a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:", a + b)  # Element-wise addition
print("a-b:", a - b)  # Element-wise subtraction
print("a*b:", a * b)  # Element-wise multiplication
print("a/b:", a / b)  # Element-wise division
print("a**2:", a ** 2)  # Element-wise exponentiation

# Broadcasting
c = np.array([[1,2,3], [4,5,6]])
d = np.array([1, 1, 1])
print("Broadcasting sum:\n", c + d)  # Adds d to each row of c


a+b: [5 7 9]
a-b: [-3 -3 -3]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]
a**2: [1 4 9]
Broadcasting sum:
 [[2 3 4]
 [5 6 7]]


In [6]:
# --------------------------------------------
# 5. Universal Functions (ufuncs)
# --------------------------------------------

arr = np.array([1, 4, 9, 16])
print("sqrt:", np.sqrt(arr))  # Square root
print("exp:", np.exp(arr))    # Exponential
print("log:", np.log(arr))    # Natural logarithm
print("sin:", np.sin(arr))    # Sine function
print("cos:", np.cos(arr))    # Cosine function


sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log: [0.         1.38629436 2.19722458 2.77258872]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [7]:
# --------------------------------------------
# 6. Aggregation Functions
# --------------------------------------------

arr = np.array([[1,2,3], [4,5,6]])
print("Sum of all elements:", np.sum(arr))  # 21
print("Sum axis 0 (columns):", np.sum(arr, axis=0))  # [5 7 9]
print("Sum axis 1 (rows):", np.sum(arr, axis=1))  # [ 6 15]
print("Mean of all elements:", np.mean(arr))  # 3.5
print("Max:", np.max(arr))  # 6
print("Min:", np.min(arr))  # 1
print("Argmax:", np.argmax(arr))  # 5 (index of max element)
print("Argmin:", np.argmin(arr))  # 0 (index of min element)
print("Standard Deviation:", np.std(arr))  # Standard deviation
print("Variance:", np.var(arr))  # Variance


Sum of all elements: 21
Sum axis 0 (columns): [5 7 9]
Sum axis 1 (rows): [ 6 15]
Mean of all elements: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665


In [8]:
# --------------------------------------------
# 7. Reshaping and Flattening
# --------------------------------------------  
arr = np.arange(12)  # 1D array with 12 elements
print("Original array:", arr)
arr_reshaped = arr.reshape((3,4))  # Reshape to 3x4
print("Reshaped array (3x4):\n", arr_reshaped)
arr_flat = arr_reshaped.flatten()  # Flatten back to 1D
print("Flattened array:", arr_flat)
arr_transpose = arr_reshaped.T  # Transpose
print("Transposed array:\n", arr_transpose)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
# --------------------------------------------
# 8. Stacking and Splitting
# --------------------------------------------

a = np.array([1,2,3])
b = np.array([4,5,6])
print("Vertical Stack:\n", np.vstack((a, b)))  # Vertical stacking
print("Horizontal Stack:", np.hstack((a, b)))  # Horizontal stacking

arr = np.arange(9)
print("Original array:", arr)
arr_split = np.split(arr, 3)  # Split into 3 equal parts
print("Split arrays:", arr_split)  # [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]
Original array: [0 1 2 3 4 5 6 7 8]
Split arrays: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [10]:
# --------------------------------------------
# 9. Copying and Views
# --------------------------------------------

arr = np.array([1,2,3,4])
arr_view = arr.view()  # Create a view
arr_copy = arr.copy()  # Create a copy
arr_view[0] = 100
arr_copy[1] = 200
print("Original array after modifying view:", arr)  # View modification affects original
print("Original array after modifying copy:", arr)  # Copy remains unchanged

Original array after modifying view: [100   2   3   4]
Original array after modifying copy: [100   2   3   4]


In [11]:
# --------------------------------------------
# 10. Boolean Indexing & Fancy Indexing
# --------------------------------------------

arr = np.array([10, 20, 30, 40, 50])
print("Elements > 25:", arr[arr > 25])  # [30 40 50]
indices = [0, 2, 4]
print("Fancy indexing:", arr[indices])  # [10 30 50]

Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [12]:
# --------------------------------------------
# 11. Random Numbers
# --------------------------------------------

rand_arr = np.random.rand(3,3)  # 3x3 array of random floats [0.0, 1.0)
print("Random 3x3 array:\n", rand_arr)

rand_int = np.random.randint(0, 10, 5)
print("Random integers between 0 and 10:", rand_int)  # 5 random integers

normal_arr = np.random.randn(3,3) # standard normal distribution
print("3x3 array from standard normal distribution:\n", normal_arr)


Random 3x3 array:
 [[0.22797748 0.07935736 0.55242708]
 [0.75476886 0.86812966 0.60395839]
 [0.49243154 0.75159506 0.25936988]]
Random integers between 0 and 10: [5 6 6 0 1]
3x3 array from standard normal distribution:
 [[ 0.68124705  0.50810855  0.31699525]
 [-1.20632537  1.46308216  1.45691885]
 [-0.28089659 -0.95210422 -0.7201943 ]]


In [13]:
# --------------------------------------------
# 12. Linear Algebra Functions
# --------------------------------------------

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print("Matrix Multiplication:\n", np.dot(A,B))  # Matrix multiplication
print("Determinant of A:", np.linalg.det(A))  # Determinant
print("Inverse of A:\n", np.linalg.inv(A))  # Inverse
print("Eigenvalues and Eigenvectors of A:\n", np.linalg.eig(A))  # Eigenvalues and Eigenvectors

Matrix Multiplication:
 [[19 22]
 [43 50]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and Eigenvectors of A:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
# --------------------------------------------
# 13. Saving and Loading Arrays
# --------------------------------------------

np.save('array_data.npy', arr_2d)  # Save array to file
loaded_arr = np.load('array_data.npy')  # Load array from file
print("Loaded array from file:\n", loaded_arr)



Loaded array from file:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

All major NumPy functions executed successfully!
